### ISSUE TITLE
-[BidaliWebViewController close]: unrecognized selector sent to instance 0x7f9707e5f340

### ISSUE THREAD

**Issue by haulevan** [bidalihq/commerce-sdk-ios#3]
Click Close button before the webview's content is loaded successfully and got this crash:

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[BidaliWebViewController close]: unrecognized selector sent to instance 0x7f9707e5f340'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23b98bde __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff503b5b20 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23bb9704 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   UIKitCore                           0x00007fff47190773 -[UIResponder doesNotRecognizeSelector:] + 302
	4   CoreFoundation                      0x00007fff23b9d7bc ___forwarding___ + 1436
	5   CoreFoundation                      0x00007fff23b9f6c8 _CF_forwarding_prep_0 + 120
	6   UIKitCore                           0x00007fff47163d19 -[UIApplication sendAction:to:from:forEvent:] + 83
	7   UIKitCore                           0x00007fff46b55599 -[UIControl sendAction:to:forEvent:] + 223
	8   UIKitCore                           0x00007fff46b558e3 -[UIControl _sendActionsForEvents:withEvent:] + 398
	9   UIKitCore                           0x00007fff46b54842 -[UIControl touchesEnded:withEvent:] + 481
	10  UIKitCore                           0x00007fff4719e21f -[UIWindow _sendTouchesForEvent:] + 2604
	11  UIKitCore                           0x00007fff4719fb26 -[UIWindow sendEvent:] + 4596
	12  UIKitCore                           0x00007fff4717b1a7 -[UIApplication sendEvent:] + 356
	13  UIKitCore                           0x00007fff471faa18 __dispatchPreprocessedEventFromEventQueue + 6847
	14  UIKitCore                           0x00007fff471fd4de __handleEventQueueInternal + 5980
	15  CoreFoundation                      0x00007fff23afbac1 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	16  CoreFoundation                      0x00007fff23afb9ec __CFRunLoopDoSource0 + 76
	17  CoreFoundation                      0x00007fff23afb21c __CFRunLoopDoSources0 + 268
	18  CoreFoundation                      0x00007fff23af5ecf __CFRunLoopRun + 1263
	19  CoreFoundation                      0x00007fff23af56b6 CFRunLoopRunSpecific + 438
	20  GraphicsServices                    0x00007fff3815cbb0 GSEventRunModal + 65
	21  UIKitCore                           0x00007fff47162a67 UIApplicationMain + 1621
	22  TestApp                             0x0000000104b8887b main + 75
	23  libdyld.dylib                       0x00007fff5123bcf5 start + 1
	24  ???                                 0x0000000000000001 0x0 + 1
)

**Comment by corymsmith** [comment]
This has been fixed in 0.0.4
